version: '3.8'

services:
  tox:
    image: ghcr.io/mmbesar/tox-container:latest
    container_name: tox
    user: "1000:1000"  # Critical: container expects to run as tox user
    networks:
      - ${NETWORK}
    environment:
      TZ: ${TZ}
      TOX_PORT: 33445
      TOX_MOTD: "Local Tox Bootstrap Node"
    volumes:
      - ${CONTAINER_DIR}/tox/data:/var/lib/tox-bootstrapd
    ports:
      - "33445:33445/tcp"
      - "33445:33445/udp"
    restart: unless-stopped
    
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "netstat", "-tuln", "|", "grep", ":33445"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  tox-data:
